# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hexo
image: node:8

pages:
  script:
    - npm install
    - node ./dataFetcherFromFavorites.js
    - node ./dataFetcherFromAPI.js
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
  only:
    - master
